# Andrew Disley: Front-end Skeleton
# http://github.com/andrewdisley/front-end-skeleton

# Minimal configuration see https://github.com/mojombo/jekyll/wiki/Configuration for full options

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

# Author
author: "Andrew Disley"
author_url: "http://simplified.co.uk/"
author_twitter: http://twitter.com/andrewdisley

# Site Title, Site Name (used for compressed js) Site ID (used on <body> element), Domain, URLs, Google Analytics ID
title: "Front-end Skeleton"
name: "frontendskeleton"
id: frontendskeleton
domain: frontendskeleton.co.uk
url: /
assets_url: /assets/
#assets_cache_buster: ?v=0.1
google_analytics_id: UA-XXXXX-XX

# Set the environment used to include production specific assets and enable Google Analytics
# development, staging, production
env: development

# Excluded files, jekyll excludes files that begin with an underscore
exclude: ['.htaccess', 'README', 'Rakefile']